# Generated by Django 4.2.1 on 2023-05-19 13:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=144)),
                ('date', models.DateTimeField(default=datetime.datetime(2023, 5, 19, 13, 26, 51, 926481, tzinfo=datetime.timezone.utc))),
            ],
        ),
    ]
