# Generated by Django 4.2.1 on 2023-05-19 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0004_alter_tweet_options_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['date']},
        ),
    ]
