# Generated by Django 4.2.1 on 2023-05-23 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0006_remove_comment_likes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date']},
        ),
    ]
