# Generated by Django 4.2.1 on 2023-05-25 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0010_remove_tweet_likes_tweet_likes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweet',
            options={'ordering': ['-date']},
        ),
    ]
